---
project_name: podinfo
dist: bin
gomod:
  env:
    - GOPRIVATE=github.com/da-moon/podinfo
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - id: "podinfo"
    mod_timestamp: "{{ .CommitTimestamp }}"
    main: ./cmd/podinfo
    env:
      - GOPRIVATE=github.com/da-moon/podinfo
      - GO111MODULE=on
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -extldflags '-static'
      - -X {{.Env.GOPRIVATE}}/build/go/version.Revision={{.FullCommit}}
      - -X {{.Env.GOPRIVATE}}/build/go/version.Branch={{.Branch}}
      - -X {{.Env.GOPRIVATE}}/build/go/version.BuildDate={{.Date }}
      - -X {{.Env.GOPRIVATE}}/build/go/version.BuildUser={{.Env.USER }}
      - -X {{.Env.GOPRIVATE}}/build/go/version.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
snapshot:
  name_template: "{{ .Tag }}"
release:
  name_template: "v{{.Version}}"
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
changelog:
  sort: asc
