---
dictionaryDefinitions:
  - name: golang
    path: ./.cspell/golang.txt
    addWords: true
  - name: generic
    path: ./.cspell/generic.txt
    addWords: true
dictionaries:
  - generic
  - golang
ignorePaths:
  - ./.cspell/*
  - ./.vscode/*
  - ./.devcontainer/*
