---
name: "docker"
on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/docker.yml"
      - "contrib/docker/*"
  pull_request:
    branches: [ master ]
jobs:
  release-amd:
    name: "build and push docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: "Login to Docker Container Repository"
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: "build and push docker image"
        shell: bash
        run: |
          set -ex ;
          docker buildx create \
            --use \
            --name "$(basename -s ".git" "$(git remote get-url origin)")" \
            --driver docker-container
  release-arm64:
    name: "build and push docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: "Login to Docker Container Repository"
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: "build and push docker image"
        shell: bash
        run: |
          set -ex ;
          docker buildx create \
            --use \
            --name "$(basename -s ".git" "$(git remote get-url origin)")" \
            --driver docker-container
