name: go
on:
  push:
    paths:
      - '**.go'
      - '.github/workflows/go.yml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Setup Go
      id: go-init
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.20'
    - name: Test Go install
      id: go-version
      run: go version
    - name: "install gorc"
      shell: bash
      run: |
        set -ex ;
        go install -v "github.com/stretchr/gorc"
    - name: "Run Unit Tests"
      id: test
      uses: magefile/mage-action@v2
      with:
        version: latest
        args: -d "build/go" -w . "test"
    - name: "Build Binary"
      id: build
      uses: magefile/mage-action@v2
      with:
        version: latest
        args: -d "build/go" -w . "build"
